service: backend
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-localstack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

custom:
  esbuild:
    bundle: true
    minify: true
    target: node16
  localstack:
    stages:
      - dev
    lambda:
      mountCode: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
